name = "Zephyr's Wake"
author = "Qwertik"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fea4aa2b3d4d05cc9df39801580b417998ab87b8fd11f5e7c76f38f273bbf92a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
