name = "Zephyr's Wake"
author = "Qwertik"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c96ab6f6cb3667480495066a7be00c69a0991437ddf861cc0cb81647e457ee91"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
