name = "Zephyr's Wake"
author = "Qwertik"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "63516cbbc3000600e9b151a09c03280c35be4d8604a15050b2a35b347e10722c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
